%% File: pstd3.f90
%% Depends on: phost, sbes, usefulsubs, constants, fftw, helpers, propagator, pscommandline, stdlog, types
graph TD
    pstd3[pstd3] --> phost[phost]
    pstd3[pstd3] --> sbes[sbes]
    pstd3[pstd3] --> usefulsubs[usefulsubs]
    pstd3[pstd3] --> constants[constants]
    pstd3[pstd3] --> fftw[fftw]
    pstd3[pstd3] --> helpers[helpers]
    pstd3[pstd3] --> propagator[propagator]
    pstd3[pstd3] --> pscommandline[pscommandline]
    pstd3[pstd3] --> stdlog[stdlog]
    pstd3[pstd3] --> types[types]
