%% File: SBEs.f90
%% Depends on: coulomb, dcfield, dephasing, emission, epsrtl, phonons, qwoptics, usefulsubs, constants, fftw, helpers, spliner, strings, types
graph TD
    sbes[sbes] --> coulomb[coulomb]
    sbes[sbes] --> dcfield[dcfield]
    sbes[sbes] --> dephasing[dephasing]
    sbes[sbes] --> emission[emission]
    sbes[sbes] --> epsrtl[epsrtl]
    sbes[sbes] --> phonons[phonons]
    sbes[sbes] --> qwoptics[qwoptics]
    sbes[sbes] --> usefulsubs[usefulsubs]
    sbes[sbes] --> constants[constants]
    sbes[sbes] --> fftw[fftw]

    sbes[sbes] --> helpers[helpers]
    sbes[sbes] --> spliner[spliner]
    sbes[sbes] --> strings[strings]
    sbes[sbes] --> types[types]
