%% File: dcfield.f90
%% Depends on: usefulsubs, constants, fftw, helpers, spliner, types
graph TD
    dcfield[dcfield] --> usefulsubs[usefulsubs]
    dcfield[dcfield] --> constants[constants]
    dcfield[dcfield] --> fftw[fftw]
    dcfield[dcfield] --> helpers[helpers]
    dcfield[dcfield] --> spliner[spliner]
    dcfield[dcfield] --> types[types]
