%% File: correlations.f90
%% Depends on: constants, fftw, helpers, propagator, pscommandline, spliner, stdlog, strings, types
graph TD
    correlations[correlations] --> constants[constants]
    correlations[correlations] --> fftw[fftw]
    correlations[correlations] --> helpers[helpers]
    correlations[correlations] --> propagator[propagator]
    correlations[correlations] --> pscommandline[pscommandline]
    correlations[correlations] --> spliner[spliner]
    correlations[correlations] --> stdlog[stdlog]
    correlations[correlations] --> strings[strings]
    correlations[correlations] --> types[types]
