%% File: pstd.f90
%% Depends on: phost, sbes, usefulsubs, constants, fftw, helpers, propagator, pscommandline, stdlog, types
graph TD
    pstd[pstd] --> phost[phost]
    pstd[pstd] --> sbes[sbes]
    pstd[pstd] --> usefulsubs[usefulsubs]
    pstd[pstd] --> constants[constants]
    pstd[pstd] --> fftw[fftw]
    pstd[pstd] --> helpers[helpers]
    pstd[pstd] --> propagator[propagator]
    pstd[pstd] --> pscommandline[pscommandline]
    pstd[pstd] --> stdlog[stdlog]
    pstd[pstd] --> types[types]
