%% File: emission.f90
%% Depends on: usefulsubs, constants, fftw, helpers, spliner, types
graph TD
    emission[emission] --> usefulsubs[usefulsubs]
    emission[emission] --> constants[constants]
    emission[emission] --> fftw[fftw]
    emission[emission] --> helpers[helpers]
    emission[emission] --> spliner[spliner]
    emission[emission] --> types[types]
