%% File: phonons.f90
%% Depends on: usefulsubs, constants, fftw, helpers, spliner, types
graph TD
    phonons[phonons] --> usefulsubs[usefulsubs]
    phonons[phonons] --> constants[constants]
    phonons[phonons] --> fftw[fftw]
    phonons[phonons] --> helpers[helpers]
    phonons[phonons] --> spliner[spliner]
    phonons[phonons] --> types[types]
